# Generated by Django 5.2 on 2025-05-01 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_key', models.CharField(max_length=50)),
                ('trigger_value', models.FloatField(blank=True, null=True)),
                ('threshold_type', models.CharField(max_length=10)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('triggering_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='readings.sensorreading')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
